# timeout
timeout = "1200s"
# your website url
baseURL = 'https://hdzh.me'
# website title
title = "Diego's digital garden"
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'es'

# theme as module
[module]
replacements = "github.com/Sped0n/bridget -> bridget"
[[module.imports]]
path = "github.com/Sped0n/bridget"
